flathub/org.signal.Signal

- org.signal.Signal.appdata.xml
If these entries are not enforced (the current build doesn't have this and works fine) why do we need the releases?
> add version 1.2.0 to appdata.xml

- org.signal.Signal.json
Exactly what it says on the tin. Hopefully this will fix some weird glitches and performance issues not seen in the uncontained app.
> Update Freedesktop Runtime to 18.08

- .gitmodules
- org.signal.Signal.json
Signal has to be started with --use-tray-icon to make it work.
Fixes #73
> Add appindicator support

- org.signal.Signal.json
Also move `TMPDIR` to `$XDG_RUNTIME_DIR/app/$FLATPAK_ID` which is better because it's not persistent as original `/tmp` would be.
> Use zypak-wrapper instead of disabling sandbox

- org.signal.Signal.appdata.xml
Emphasized text is not being rendered, so I decided to remove the `<em>` tags for now.
Edit: See https://github.com/flathub/linux-store-frontend/issues/203
> Remove <em> tags from description

- org.signal.Signal.json
Those are available in baseapp[1], building them one more time is redundant.
[1] https://github.com/flathub/org.electronjs.Electron2.BaseApp/blob/branch/19.08/org.electronjs.Electron2.BaseApp.yml#L21
> Stop duplicating shared-modules from baseapp

- org.signal.Signal.appdata.xml
- org.signal.Signal.json
A release was made https://github.com/signalapp/Signal-Desktop/releases/tag/v1.34.5 a few days ago
This PR is to update to that release
> Update to v1.34.5

- org.signal.Signal.json
* Improve sandbox security by change the "--filesystem" flag from
"home" to "xdg-download". This means Signal can only access the
XDG Download folder of the user instead of full access to home
folder.
* Resolve #153.
> Limit the filesystem to download folder only

- org.signal.Signal.json
Remove hardcoded reference of `own-name`. This could lead to problems with other apps that have the same own-name.
> Fix tray icon with KDE Status Notifier

- org.signal.Signal.json
If `DISPLAY` is unset and `WAYLAND_DISPLAY` is set, force using the
wayland backend. This scenario will only happen when a user explicitly
adds overrides to their local Flatpak configuration, e.g.:
$ cat ~/.local/share/flatpak/overrides/org.signal.Signal
[Context]
sockets=wayland;!x11
This changeset has no effect on the default setup, and won't affect
users unless they take manual action to disable the X11 socket.
> Enable Wayland backend if it's the only choice

- org.signal.Signal.yaml
Using `--socket=x11` results in GNOME Software showing the app as "Unsafe. Uses a legacy windowing system." Changing this to `--socket=fallback-x11` lets app run on Wayland but can use X11 if Wayland not available
> Change socket to fallback-x11 to remove "Unsafe" warning

- org.signal.Signal.metainfo.xml
- org.signal.Signal.yaml
- signal-desktop.sh
This enables users that want the tray icon to pass the environment variable $SIGNAL_USE_TRAY_ICON (either on terminal, desktop file, or flatseal) to have a consistent behavior for the tray icon.
The value can be anything, if it's declared, it will add the `--use-tray-icon` option to the starting command.
(I don't know who will use this anyway, because it's not advertised anywhere.)
> [WIP] Allow env SIGNAL_USE_TRAY_ICON to set tray icon

- README.md
- org.signal.Signal.yaml
- signal-desktop.sh
The Signal launcher script checks for numerous variables to pass
CLI arguments. This change has them set directly by flatpak so
that they can be visible in frontends like Flatseal. This change
also switches from checking for set variables to instead test
numerical values which is generally more consistent in Bash.
> Have flatpak set environment variables for greater visability

- org.signal.Signal.yaml
This will help keep Signal up to date with the newest Freedesktop runtime.
> Update Freedesktop SDK to 22.08

- README.md
Removing the error reporting section of the README since it's already included at the bottom.
> remove repeat info in README

- .github/workflows/update-beta.yaml
The default master branch is already checked by flathub's external data checker.
> CI: Only update beta branch automatically

- org.signal.Signal.yaml
Add - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons to fix the mouse theming issue when wayland forced without downside on X11 user
It fix this issue : https://github.com/flathub/org.signal.Signal/issues/375
> Fix mouse theming issue on wayland

- org.signal.Signal.yaml
xdg-portal filepicker already allows the user to choose files, without sharing entire directories to the sandbox.
> Remove unnecessary permissions

- org.signal.Signal.yaml
xdg-portal filepicker already allows the user to choose files, without sharing entire directories to the sandbox
> Remove unnecessary permissions (#438)

- org.signal.Signal.metainfo.xml
The project_license field should contain the SPDX name of the wrapped
application.
Signal uses [AGPLv3](https://opensource.org/license/agpl-v3/) which uses
`AGPL-3.0-only` as SPDX short identifier
> fix license

- org.signal.Signal.yaml
This is no longer required with newer Electron and runtime
https://docs.flatpak.org/en/latest/desktop-integration.html#statusnotifier
> Most implementations of StatusNotifer have dropped this requirement
> but known exceptions to this are Electron versions older than 23.3.0.
Current version uses Electron 25.8.1
https://github.com/signalapp/Signal-Desktop/blob/67c1f2af14ed1de74914e3b028835e679561d458/yarn.lock#L9272
> Drop `org.kde.*` own-name

- org.signal.Signal.yaml
23.08 baseapp uses libnotify 0.8.2 which uses portals for notifications
https://gitlab.gnome.org/GNOME/libnotify/-/blob/69aff6e5fa2842e00b409c348bd73188548828b3/NEWS#L25
Note. if the runtime update gets reverted at any point this needs to be reverted as well.
> Remove org.freedesktop.Notifications

- org.signal.Signal.yaml
This is needed to prevent the screen from powering off during video calls.
dbus names taken from here:
https://source.chromium.org/chromium/chromium/src/+/main:services/device/wake_lock/power_save_blocker/power_save_blocker_linux.cc;l=33;drc=f1f723353c6ed4d33694e8f2fad1b983f813006c
> Add dbus permission for inhibiting sleep/screensaver

- README.md
- org.signal.Signal.yaml
- signal-desktop.sh
Since Electron 26 flag `--enable-features=WaylandWindowDecorations` is automatically enabled when running on wayland the environment variable is not needed anymore.
> Enable automatic selection of Wayland/X11

- README.md
- org.signal.Signal.yaml
- signal-desktop.sh
Hi, since a few releases it's possible to customize both options through settings GUI so they are no longer needed.
> Remove tray environment variables

- org.signal.Signal.metainfo.xml
- org.signal.Signal.yaml
This reverts commit ac1ca491ad3c56894d49a9ba6470030301f108ab.
The file portals are not used with this version.
> Revert "signal-desktop: Update signal-desktop.deb to 7.25.0 (#718)"

- org.signal.Signal.yaml
Let's make use of the updated runtime & SDKs:
https://discourse.flathub.org/t/freedesktop-sdk-24-08-0-released/7630
Changes were tested and found working without any issues on my side, but further testing would be highly appreciated!
> Use freedesktop 24.08 SDK & runtime

- org.signal.Signal.yaml
This reverts commit f88079a969bfcfbf33af95123418e632c44d2371.
The name is in lowercase:
```
dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.ListNames|grep secrets
string "org.freedesktop.secrets"
```
> Revert "Fix capitalization"

- org.signal.Signal.metainfo.xml
- org.signal.Signal.yaml
Ideally, upstream will also migrate to `org.signal.Signal.desktop`. This fixes task manager icons on KDE Plasma 6.1.5.
AppStream gained `<provides><id>…` per a recommendation from <https://blogs.gnome.org/hughsie/2019/04/23/remember-the-extra-metadata-if-you-change-a-desktop-id/>.
> Migrate from `signal.desktop` to `org.signal.Signal.desktop`

- README.md
- org.signal.Signal.yaml
- signal-desktop.sh
> Add environment variable to select storage provider

- org.signal.Signal.metainfo.xml
- org.signal.Signal.yaml
Upstream calls their desktop file `signal-desktop.desktop`
> Use correct desktop file name

- org.signal.Signal.metainfo.xml
- org.signal.Signal.yaml
- signal-desktop.sh
This is necessary because Electron broke the portals.
Also, adding specific folders like xdg-downloads, xdg-pictures, xdg-videos, and such will never satisfy everybody.
> Allow filesystem=host (show information once)

- org.signal.Signal.yaml
If you previously had `basic` storage, run it as `flatpak run --env=SIGNAL_PASSWORD_STORE=gnome-libsecret org.signal.Signal` and check if it's storing in the keyring correctly.
> Build libsecret without gcrypt

- signal-desktop.sh
It requires testing from people on different DEs but also checking if IMEs work.
> Enable input method when ELECTRON_OZONE_PLATFORM_HINT=auto or ELECTRON_OZONE_PLATFORM_HINT=wayland

- org.signal.Signal.metainfo.xml
cf. https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines#url
> metainfo: add URL to source repo

- org.signal.Signal.metainfo.xml
- org.signal.Signal.yaml
Manual update because f-e-d-c didn't find the update.
> Update to 7.49.0

- README.md
- signal-desktop.sh
Chromium 140, on which Electron 38 is based, uses the Wayland Ozone backend by default. In this context, the Chromium command line argument `--ozone-platform-hint` has been removed as it is no longer needed. Due to this removal, the Electron environment variable `ELECTRON_OZONE_PLATFORM_HINT` no longer has any effect.
Upstream issue: https://github.com/electron/electron/issues/48001
> Remove unnecessary environment variable `ELECTRON_OZONE_PLATFORM_HINT`

- signal-desktop.sh
Signal 7.73.0 uses Electron 38.2.0 which includes the fix for the broken wayland detection (https://github.com/electron/electron/pull/48309).
> Remove workaround for Electron's broken wayland detection
