flathub/org.signal.Signal

org.signal.Signal.json
=> Update to 1.0.37

org.signal.Signal.appdata.xml, org.signal.Signal.json
Changelog here: https://github.com/WhisperSystems/Signal-Desktop/releases/tag/v1.0.41
=> Update to 1.0.41

org.signal.Signal.json
Hi there,
I don't really know how to test build with this new version, so if you have any advice, I'm here to ear. :-)
=> Update to 1.2.0

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> update to v1.11.0

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.14.1

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.16.1

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.17.3

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.23.0

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.26.0

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.26.1

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.26.2

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.27.1

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.28.0

org.signal.Signal.json
=> Update runtime and base to 19.08

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.29.0

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.29.2

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.29.3

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.26.4

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.29.6

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.30.1

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.31.0

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.32.0

org.signal.Signal.appdata.xml, org.signal.Signal.json
=> Update to v1.33.0

org.signal.Signal.appdata.xml, org.signal.Signal.json
Signal added voice and video calls in this latest update. I'd love to see this on flathub.
=> Update to v1.35.1

org.signal.Signal.json
This enables webcam support in the flatpak
=> Enabling camera in flatpak by setting "--device=all"

org.signal.Signal.json
Enable access to wayland for #188
=> Give Wayland access

org.signal.Signal.yaml
=> Don't fallback to x11 on wayland.

flathub.json
The updates from upstream seem to be stable enough to be accepted automatically.
=> Update flathub.json (#385)

org.signal.Signal.yaml
=> Readd own name

.github/workflows/update-beta.yaml
From https://github.com/flathub/flatpak-external-data-checker/issues/352, this workaround let's us update beta branch again.
=> Fix beta update check

.github/workflows/update-beta.yaml
=> Update update-beta.yaml (#415)

org.signal.Signal.yaml
This allows Signal to access the system bus, for more information see: https://github.com/flathub/org.signal.Signal/issues/280
=> Add access to system bus

org.signal.Signal.yaml
=> Update to runtime 23.08

org.signal.Signal.yaml
Apps shouldn't add portals manually.
=> Remove Background portal

org.signal.Signal.yaml
=> use id instead of app-id

README.md, org.signal.Signal.yaml, signal-desktop-beta.sh
=> Enable automatic selection of Wayland/X11 (#572)

README.md, org.signal.Signal.yaml, signal-desktop-beta.sh
This reverts commit 0c8992177d41a007dddefd6c5c19696bbea26f97.
=> Revert "Enable automatic selection of Wayland/X11 (#572) (#578)"

org.signal.Signal.metainfo.xml, org.signal.Signal.yaml, signal-desktop.sh
Add latest changes from master
* also maybe? add fewer maintenance steps for master/beta branches
=> Align master

README.md, signal-desktop.sh
Show the encryption warning only once.
=> Show encryption notification only once

.editorconfig
See https://github.com/flathub-infra/flatpak-external-data-checker/issues/280
=> Prevent flathubbot from wrapping long lines

org.signal.Signal.yaml
- https://github.com/flathub-infra/flatpak-external-data-checker?tab=readme-ov-file#anitya-release-monitoring-checker
- https://release-monitoring.org/project/13150/
=> libsecret: configure Flatpak External Data Checker

org.signal.Signal.yaml
This should fix https://github.com/flathub/org.signal.Signal/issues/852
=> Fix the notification count badge on KDE

org.signal.Signal.metainfo.xml, org.signal.Signal.yaml
Fixes https://github.com/flathub/org.signal.Signal/issues/879
=> manual update for 7.53.0

org.signal.Signal.yaml
This requires testing on different DEs before merging.
=> feat(manifest): switch socket from x11 to fallback-x11
